[project]
name = "Dota-bot"
version = "0.1.0"
description = ""
authors = [
    {name = "Behnam Khalili",email = "you@example.com"},
    {name = "Mohammadreza Afshar",email = "realmohammadrezaafshar@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests (>=2.32.4,<3.0.0)",
    "pydantic (>=2.11.9,<3.0.0)",
    "sqlalchemy (>=2.0.43,<3.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
    "psycopg2 (>=2.9.11,<3.0.0)",
    "alembic (>=1.19.1,<2.0.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)",
]

[tool.poetry]
packages = [{include = "api_clients", from = "src"}]


[tool.ruff]
line-length = 88
src = ["src"]

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.pyright]
pythonVersion = "3.12"
pythonPlatform = "Linux"
extraPaths = ["src"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff (>=0.16.2,<0.17.0)"
]
