"""add lastMatchTime to dim_player

Revision ID: 35a7b0d55459
Revises: 9d3d3fae8bc1
Create Date: 2026-08-21 19:40:17.485642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a7b0d55459'
down_revision: Union[str, Sequence[str], None] = '9d3d3fae8bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dim_player', sa.Column('lastMatchTime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dim_player', 'lastMatchTime')
    # ### end Alembic commands ###
