"""initial schema

Revision ID: 4b8968fbae83
Revises:
Create Date: 2026-08-09 04:08:08.048431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8968fbae83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dim_hero', ['heroId'])
    op.create_unique_constraint(None, 'dim_item', ['itemId'])
    op.create_unique_constraint(None, 'dim_player', ['id'])
    op.create_unique_constraint(None, 'fact_item_purchase', ['id'])
    op.create_unique_constraint(None, 'fact_match', ['matchId'])
    op.create_unique_constraint(None, 'fact_player_match', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fact_player_match', type_='unique')
    op.drop_constraint(None, 'fact_match', type_='unique')
    op.drop_constraint(None, 'fact_item_purchase', type_='unique')
    op.drop_constraint(None, 'dim_player', type_='unique')
    op.drop_constraint(None, 'dim_item', type_='unique')
    op.drop_constraint(None, 'dim_hero', type_='unique')
    # ### end Alembic commands ###
